# Netlify configuration for yalokgar.com

[build]
  # Static site root (index.html in project root)
  publish = "."

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # CSP allows our local assets and HTTPS images (GitHub stats widgets), blocks everything else
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; img-src 'self' https: data:; font-src 'self' data: https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; upgrade-insecure-requests"

# Caching: long cache for static assets, no-cache for HTML documents
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/404.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/photo_2025-05-15_16-53-42.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Canonical domain: force HTTPS and apex (yalokgar.com)
[[redirects]]
  from = "http://yalokgar.com/*"
  to = "https://yalokgar.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.yalokgar.com/*"
  to = "https://yalokgar.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.yalokgar.com/*"
  to = "https://yalokgar.com/:splat"
  status = 301
  force = true

# Serve favicon from site root path for broad client compatibility
[[redirects]]
  from = "/favicon.ico"
  to = "/photo_2025-05-15_16-53-42.jpg"
  status = 200
  force = true
